[build]
target = "x86_64-unknown-none"
features = ["-mmx", "-sse", "-sse2", "-avx", "-avx2", "-red-zone"]

[target.x86_64-unknown-none]
rustflags = ["-C", "link-arg=-Tlinker.ld"]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"] # On empêche de lier la crate test
build-std-features = ["compiler-builtins-mem"]
